# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WeiNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Masonry', '~> 1.0.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'FMDB', '~> 2.6.2'
    pod 'MBProgressHUD'
    pod 'YYText'
    pod 'YYModel'
    pod 'YYWebImage'


  # Pods for WeiNews

end
